# Generated by Django 2.2.1 on 2019-06-20 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demotable',
            name='image',
            field=models.ImageField(upload_to='photos'),
        ),
    ]
